### PR TITLE
Fix docker-test commands

### PR DESCRIPTION
**Pull request by AdamZaczek**
In #82 there's a description of a bug occurring when running ``yarn docker-test``. This pull aims to fix it.

### CODE REVIEW

**Comment by koistya** [comment]
Hi Adam, thanks for the PR! It will not work as expected, because the first portion of the command, before `&&` will be executed inside Docker (it will install NPM packages inside the container), and the second portion, after `&&` will run tests using local NPM modules (which may differ depending on your dev OS, e.g. Windows in dev vs Linux inside Docker).

**Comment by AdamZaczek** [comment]
I haven't noticed, that's how I'm currently testing my app. I agree that the command should use modules from docker. Do you know how we should approach this? The script in package.json seemed broken as described in #82 . Should we make a script like the one in  tools/run.js designed for running yarn install and yarn test?

**Comment by frenzzy** [comment]
@AdamZaczek why you can't just install dependencies before running tests? It is necessary only first time
```sh
yarn run docker-install  # you don't need to call it every time, only initially
yarn run docker-test     # or yarn run docker-test-watch
```

**Comment by AdamZaczek** [comment]
@frenzzy Oh, I was 100% sure I did run it, thanks ;)

**Comment by AdamZaczek** [comment]
@frenzzy I just confirmed I did run yarn docker-install and the commands were not working. Could you see if you can reproduce the bug?

**Comment by koistya** [comment]
You can also try
```
docker-compose run api sh -c 'yarn install && yarn test'
```
or, if the container is already running:
```
docker-compose exec api sh -c 'yarn install && yarn test'
```

**Comment by AdamZaczek** [comment]
I like how simple this solution is, thanks @koistya

**Comment by koistya** [comment]
@AdamZaczek I have updated the app launcher script to always run `yarn install` before launching the up inside docker. In other words, whenever you run `docker-compose up` it will ensure that all the Node.js dependencies are up to date. No need run this command over again in `docker-compose api yarn test`.

https://github.com/kriasoft/nodejs-api-starter/blob/master/tools/run.js#L32-L33

**Pull request closed without merging**
